version: '3.4'

services:
  job.starter:
    image: ${DOCKER_REGISTRY-}job
    build:
      context: .
      dockerfile: job.starter/Dockerfile
    environment:
      YAML: ./config/job.yaml
    volumes:
      - ./config:/app/config
      - $HOME/.kube:/root/.kube
